(function(){
const languages=[['en','🇬🇧','English'],['de','🇩🇪','German'],['pt','🇵🇹','Portuguese'],['es','🇪🇸','Spanish'],['fr','🇫🇷','French'],['it','🇮🇹','Italian'],['ru','🇷🇺','Russian'],['ko','🇰🇷','Korean'],['ja','🇯🇵','Japanese'],['ar','🇸🇦','Arabic'],['th','🇹🇭','Thai'],['vi','🇻🇳','Vietnamese'],['tr','🇹🇷','Turkish'],['nl','🇳🇱','Dutch'],['id','🇮🇩','Indonesian'],['iw','🇮🇱','Hebrew'],['hi','🇮🇳','Hindi']];
const style=document.createElement('style');style.textContent=`html,body{max-width:100%;overflow-x:hidden}body *{min-width:0}h1,h2,h3,p,a,span,dd{overflow-wrap:anywhere}.nav{height:auto!important;min-height:82px;gap:14px;flex-wrap:wrap}.nav nav{flex-wrap:wrap;justify-content:center}.hero,.factory,.company,.contact{height:auto!important}.hero-copy,.copy,.factory-copy,.company-copy,.contact-box{overflow:visible}.grid,.caps,.gallery-grid{grid-template-columns:repeat(auto-fit,minmax(min(260px,100%),1fr))!important}.language-switcher{position:relative;z-index:40;background:#fff;border-bottom:1px solid #e1e5df;padding:9px 4vw;overflow-x:auto;scrollbar-width:thin;direction:ltr}.language-list{display:flex;justify-content:center;gap:4px;min-width:max-content;margin:auto}.language-button{min-width:70px;padding:5px 7px;border:0;border-radius:7px;background:transparent;color:#243d34;cursor:pointer;font:11px/1.2 Arial,sans-serif;text-align:center}.language-button:hover,.language-button:focus,.language-button.active{background:#e6eddf;outline:none}.language-flag{display:block;font-size:27px;line-height:29px;margin-bottom:3px}#google_translate_element{position:absolute;left:-9999px;top:-9999px;width:1px;height:1px;overflow:hidden}.goog-te-banner-frame.skiptranslate{display:none!important}body{top:0!important}html[dir=rtl] .hero-copy,html[dir=rtl] .copy,html[dir=rtl] .factory-copy,html[dir=rtl] .company-copy,html[dir=rtl] .contact-box{text-align:right}html[dir=rtl] .fact,html[dir=rtl] dl div{direction:rtl}@media(max-width:900px){.nav nav{order:3;width:100%}.head{display:block!important}.head>p{max-width:none}.hero h1,.section h2,.company h2,.contact h2,.copy h1{font-size:clamp(38px,10vw,58px)!important}}@media(max-width:760px){.language-list{justify-content:flex-start}.language-button{min-width:63px}.hero-copy,.copy,.factory-copy,.company-copy,.contact,.section,.gallery{padding-left:5vw!important;padding-right:5vw!important}}`;document.head.appendChild(style);
const current=(document.cookie.match(/(?:^|;\s*)googtrans=\/en\/([^;]+)/)||[])[1]||'en';
document.documentElement.dir=['ar','iw'].includes(current)?'rtl':'ltr';
function switchTo(lang){document.cookie=`googtrans=/en/${lang};path=/;SameSite=Lax`;const select=document.querySelector('.goog-te-combo');if(select){select.value=lang;select.dispatchEvent(new Event('change'));setTimeout(()=>location.reload(),350)}else location.reload()}
const bar=document.createElement('div');bar.className='language-switcher';bar.setAttribute('aria-label','Choose website language');const list=document.createElement('div');list.className='language-list';languages.forEach(([code,flag,label])=>{const b=document.createElement('button');b.type='button';b.className=`language-button${current===code?' active':''}`;b.title=`View in ${label}`;b.innerHTML=`<span class="language-flag" aria-hidden="true">${flag}</span><span>${label}</span>`;b.addEventListener('click',()=>switchTo(code));list.appendChild(b)});bar.appendChild(list);const header=document.querySelector('header.nav,.nav');if(header)header.insertAdjacentElement('afterend',bar);else document.body.prepend(bar);
const mount=document.createElement('div');mount.id='google_translate_element';document.body.appendChild(mount);window.googleTranslateElementInit=()=>new google.translate.TranslateElement({pageLanguage:'en',includedLanguages:languages.map(x=>x[0]).filter(x=>x!=='en').join(','),autoDisplay:false},'google_translate_element');const script=document.createElement('script');script.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';script.async=true;document.head.appendChild(script);
const navigation=document.createElement('script');navigation.src='/navigation.js';document.head.appendChild(navigation);
})();
