(function(){
const languages=[['en','GB','English'],['de','DE','German'],['pt','PT','Portuguese'],['es','ES','Spanish'],['fr','FR','French'],['it','IT','Italian'],['ru','RU','Russian'],['ko','KR','Korean'],['ja','JP','Japanese'],['ar','SA','Arabic'],['th','TH','Thai'],['vi','VN','Vietnamese'],['tr','TR','Turkish'],['nl','NL','Dutch'],['id','ID','Indonesian'],['iw','IL','Hebrew'],['hi','IN','Hindi']];
const style=document.createElement('style');style.textContent=`html,body{max-width:100%;overflow-x:hidden}body *{min-width:0}h1,h2,h3,p,a,span,dd{overflow-wrap:anywhere}.language-switcher{position:relative;z-index:40;background:#fff;border-bottom:1px solid #e1e5df;padding:8px 4vw;overflow-x:auto;scrollbar-width:thin;direction:ltr}.language-list{display:flex;justify-content:center;gap:4px;min-width:max-content;margin:auto}.language-button{min-width:66px;padding:5px 7px;border:0;border-radius:6px;background:transparent;color:#243d34;cursor:pointer;font:10px/1.2 Arial,sans-serif;text-align:center}.language-button:hover,.language-button:focus,.language-button.active{background:#e6eddf;outline:none}.language-flag{display:block;width:30px;margin:0 auto 4px;padding:3px 0;border:1px solid #dfe4df;background:#fff;color:#075b32;font-weight:900;font-size:10px}#google_translate_element{position:absolute;left:-9999px;top:-9999px;width:1px;height:1px;overflow:hidden}.goog-te-banner-frame.skiptranslate{display:none!important}body{top:0!important}html[dir=rtl] .manufacturing-copy,html[dir=rtl] .herbal-copy,html[dir=rtl] .about-copy{text-align:right}@media(max-width:900px){.language-list{justify-content:flex-start}.language-button{min-width:62px}}`;document.head.appendChild(style);
const current=(document.cookie.match(/(?:^|;\s*)googtrans=\/en\/([^;]+)/)||[])[1]||'en';
document.documentElement.dir=['ar','iw'].includes(current)?'rtl':'ltr';
function switchTo(lang){document.cookie=`googtrans=/en/${lang};path=/;SameSite=Lax`;const select=document.querySelector('.goog-te-combo');if(select){select.value=lang;select.dispatchEvent(new Event('change'));setTimeout(()=>location.reload(),350)}else location.reload()}
const bar=document.createElement('div');bar.className='language-switcher';bar.setAttribute('aria-label','Choose website language');const list=document.createElement('div');list.className='language-list';languages.forEach(([code,flag,label])=>{const b=document.createElement('button');b.type='button';b.className=`language-button${current===code?' active':''}`;b.title=`View in ${label}`;b.innerHTML=`<span class="language-flag" aria-hidden="true">${flag}</span><span>${label}</span>`;b.addEventListener('click',()=>switchTo(code));list.appendChild(b)});bar.appendChild(list);const header=document.querySelector('header.nav,.nav');if(header)header.insertAdjacentElement('afterend',bar);else document.body.prepend(bar);
const mount=document.createElement('div');mount.id='google_translate_element';document.body.appendChild(mount);window.googleTranslateElementInit=()=>new google.translate.TranslateElement({pageLanguage:'en',includedLanguages:languages.map(x=>x[0]).filter(x=>x!=='en').join(','),autoDisplay:false},'google_translate_element');const script=document.createElement('script');script.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';script.async=true;document.head.appendChild(script);
const navigation=document.createElement('script');navigation.src='/navigation.js';document.head.appendChild(navigation);
})();
