(function(){
  const categories=[
    ['all','All Products'],['hard-capsules','Hard Capsules'],['gummies','Gummies'],
    ['softgels','Softgels'],['liquid-drops','Liquid Drops'],['powder-supplements','Powder Supplements'],
    ['effervescent-tablets','Effervescent Tablets'],['chewable-swallow-tablets','Chewable / Swallow Tablets'],
    ['shilajit-resin','Shilajit Resin'],['herbal-slices','Chinese Herbal Slices'],['herbal-beverages','Herbal Beverages']
  ];
  const css=document.createElement('style');
  css.textContent=`.nav{position:sticky!important;top:0!important;z-index:80!important;background:#0d6b36!important;color:#fff!important;border:0!important;padding:0 4vw!important;min-height:70px!important}.site-nav-brand{display:flex;align-items:center;gap:10px;color:#fff!important;font-weight:800;letter-spacing:.1em}.site-nav-brand img{width:44px;height:44px;border-radius:50%;object-fit:cover}.site-nav-menu{display:flex;align-items:stretch;gap:0}.site-nav-item{position:relative;display:flex;align-items:center}.site-nav-link,.site-nav-toggle{height:70px;display:flex;align-items:center;padding:0 24px;border:0;background:transparent;color:#fff!important;font:700 14px Arial,sans-serif;cursor:pointer}.site-nav-link:hover,.site-nav-toggle:hover,.site-nav-item.active>.site-nav-link,.site-nav-item.active>.site-nav-toggle{background:#095c2d}.site-nav-toggle:after{content:'⌄';margin-left:9px;font-size:17px}.site-nav-dropdown{display:none;position:absolute;left:0;top:70px;min-width:245px;padding:8px 0;background:#fff;color:#243d34;box-shadow:0 12px 35px #092a1c35;border-radius:0 0 5px 5px;z-index:100}.site-nav-dropdown a{display:block;padding:11px 20px;color:#243d34!important;font-size:14px;white-space:nowrap}.site-nav-dropdown a:hover{background:#edf4ee;color:#0d6b36!important}.site-nav-item:hover .site-nav-dropdown,.site-nav-item:focus-within .site-nav-dropdown,.site-nav-item.open .site-nav-dropdown{display:block}.site-nav-search{display:flex;align-items:center}.site-nav-search input{width:210px;border:0;border-radius:999px;padding:10px 16px;font-size:13px}.site-nav-mobile{display:none;border:0;background:transparent;color:#fff;font-size:25px;cursor:pointer}@media(max-width:900px){.site-nav-mobile{display:block}.site-nav-menu{display:none;position:absolute;left:0;right:0;top:70px;background:#0d6b36;flex-direction:column;align-items:stretch}.site-nav-menu.mobile-open{display:flex}.site-nav-item{display:block}.site-nav-link,.site-nav-toggle{width:100%;height:52px;justify-content:space-between;padding:0 5vw}.site-nav-dropdown{position:static;box-shadow:none;border-radius:0;background:#fff}.site-nav-search{padding:12px 5vw}.site-nav-search input{width:100%}}`;
  document.head.appendChild(css);
  const header=document.querySelector('header.nav,.nav'); if(!header)return;
  const path=location.pathname;
  const catLinks=categories.map(([slug,label])=>`<a href="/category.html?category=${slug}">${label}</a>`).join('');
  header.innerHTML=`<a class="site-nav-brand" href="/"><img src="/company-logo.jpg" alt="KUNCAIZHINEN"><span>KUNCAIZHINEN</span></a><button class="site-nav-mobile" type="button" aria-label="Open navigation">☰</button><nav class="site-nav-menu" aria-label="Main navigation"><div class="site-nav-item ${path==='/'||path.endsWith('/index.html')?'active':''}"><a class="site-nav-link" href="/">Home</a></div><div class="site-nav-item ${path.endsWith('/category.html')||path.endsWith('/product.html')?'active':''}"><button class="site-nav-toggle" type="button" aria-expanded="false">Products</button><div class="site-nav-dropdown">${catLinks}</div></div><div class="site-nav-item ${path.endsWith('/company.html')?'active':''}"><button class="site-nav-toggle" type="button" aria-expanded="false">Company Profile</button><div class="site-nav-dropdown"><a href="/company.html?section=about">Company Introduction</a><a href="/company.html?section=contact">Contact Us</a></div></div><div class="site-nav-search"><input id="site-search" type="search" placeholder="Search products" aria-label="Search products"></div></nav>`;
  const menu=header.querySelector('.site-nav-menu');
  header.querySelector('.site-nav-mobile').onclick=()=>menu.classList.toggle('mobile-open');
  header.querySelectorAll('.site-nav-toggle').forEach(button=>button.onclick=()=>{const item=button.closest('.site-nav-item');const open=!item.classList.contains('open');header.querySelectorAll('.site-nav-item').forEach(x=>x.classList.remove('open'));item.classList.toggle('open',open);button.setAttribute('aria-expanded',String(open))});
  const search=header.querySelector('#site-search');search.addEventListener('keydown',e=>{if(e.key==='Enter'&&search.value.trim())location.href='/category.html?category=all&q='+encodeURIComponent(search.value.trim())});
})();
