async function getProducts(){const response=await fetch('/products.json',{cache:'no-store'});if(!response.ok)throw new Error('Unable to load products');return (await response.json()).products||[]}
const productLayoutStyle=document.createElement('style');productLayoutStyle.textContent='.product-groups{display:block}.product-category{margin-top:70px}.product-category:first-child{margin-top:0}.category-title-row{display:flex;align-items:end;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:18px;margin-bottom:24px}.category-title-row span{font-size:9px;letter-spacing:.15em;text-transform:uppercase}.category-title-row h3{font:36px var(--serif);margin:8px 0 0}.category-product-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.category-product-grid .card img{height:300px;object-fit:contain;background:#f8f8f5}.category-product-grid .card strong{font-size:12px}.view-more{border:1px solid var(--ink);padding:12px 18px;font-size:12px;font-weight:700}.view-more:hover{background:var(--ink);color:#fff}@media(max-width:1000px){.category-product-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:850px){.category-product-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.category-title-row{align-items:center}.category-title-row h3{font-size:29px}.category-product-grid{grid-template-columns:1fr}}';document.head.appendChild(productLayoutStyle);
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function productCard(product){return `<article class="card"><a href="/product.html?slug=${encodeURIComponent(product.slug)}"><img src="${escapeHtml(product.mainImage)}" alt="${escapeHtml(product.name)}"><div><span>${escapeHtml(product.category)}</span><h3>${escapeHtml(product.name)}</h3><p>${escapeHtml(product.summary)}</p><strong>View product details &rarr;</strong></div></a></article>`}
const homeCategories=[
  ['gummies','Gummies'],['hard-capsules','Hard Capsules'],['softgels','Softgels'],
  ['liquid-drops','Liquid Drops'],['powder-supplements','Powder Supplements'],
  ['effervescent-tablets','Effervescent Tablets'],['chewable-swallow-tablets','Chewable / Swallow Tablets'],
  ['shilajit-resin','Shilajit Resin'],['herbal-slices','Chinese Herbal Slices'],['herbal-beverages','Herbal Beverages']
];
async function renderProducts(){const grid=document.querySelector('#product-grid');if(!grid)return;try{const products=(await getProducts()).filter(p=>p.featured!==false);const sections=homeCategories.map(([slug,label])=>{const group=products.filter(p=>p.categorySlug===slug);if(!group.length)return '';return `<section class="product-category"><div class="category-title-row"><div><span>Product category</span><h3>${escapeHtml(label)}</h3></div><a class="view-more" href="/category.html?category=${encodeURIComponent(slug)}">View More &rarr;</a></div><div class="grid category-product-grid">${group.slice(0,8).map(productCard).join('')}</div></section>`}).join('');grid.className='product-groups';grid.innerHTML=sections||`<article class="card more"><div><span>Portfolio-ready structure</span><h3>Products coming soon</h3><p>New products can be added from the product management panel.</p></div></article>`}catch(error){console.error(error)}}
document.addEventListener('DOMContentLoaded',renderProducts);
document.addEventListener('DOMContentLoaded',()=>{const style=document.createElement('style');style.textContent='.whatsapp-float{position:fixed;right:22px;bottom:22px;z-index:30;background:#25D366;color:#fff;padding:14px 18px;border-radius:999px;font-weight:800;font-size:14px;box-shadow:0 8px 28px #10271d45;text-decoration:none}.whatsapp-float:hover{background:#1fb85a;transform:translateY(-2px)}';document.head.appendChild(style);const button=document.createElement('a');button.className='whatsapp-float';button.href='https://wa.me/14085811840';button.target='_blank';button.rel='noopener';button.setAttribute('aria-label','Chat with us on WhatsApp');button.textContent='WhatsApp Chat';document.body.appendChild(button);const note=[...document.querySelectorAll('small')].find(el=>el.textContent.includes('WhatsApp contact'));if(note){const link=document.createElement('a');link.className='mail';link.href='https://wa.me/14085811840';link.target='_blank';link.rel='noopener';link.textContent='WhatsApp: +1 408 581 1840';note.replaceWith(link)}});
const languageScript=document.createElement('script');languageScript.src='/languages.js';languageScript.defer=true;document.head.appendChild(languageScript);
